### ISSUE TITLE
typescript@2.0.0 error -- e._compiler.getSourceFile is not a function

### ISSUE THREAD

**Issue by jperl** [wallabyjs/wallaby-typescript-sample#1]
```
[Info] Sat, 13 Aug 2016 18:42:28 GMT wallaby:project Running postprocessor
[Info] Sat, 13 Aug 2016 18:42:28 GMT wallaby:postprocessor New TypeScript language service is required
[Info] Sat, 13 Aug 2016 18:42:28 GMT wallaby:project TypeError: e._compiler.getSourceFile is not a function
[Info]   at /Users/jperl/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.20/wallaby/server.js:18:4486
[Info]   at baseFor (/Users/jperl/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.20/wallaby/node_modules/lodash/index.js:1971:13)
[Info]   at baseForOwn (/Users/jperl/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.20/wallaby/node_modules/lodash/index.js:2025:14)
[Info]   at baseEach (/Users/jperl/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.20/wallaby/node_modules/lodash/index.js:1814:16)
[Info]   at Function.forEach (/Users/jperl/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.20/wallaby/node_modules/lodash/index.js:5701:11)
[Info]   at Object.postprocessor (/Users/jperl/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.20/wallaby/server.js:18:3800)
[Info]   at /Users/jperl/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.20/wallaby/server.js:16:13886
[Info]   at [object Object]._onTimeout (/Users/jperl/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.20/wallaby/server.js:16:13488)
[Info]   at Timer.listOnTimeout (timers.js:92:15)
[Info] From previous event:
[Info]   at [object Object]._onTimeout (/Users/jperl/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.20/wallaby/server.js:16:13488)
[Info]   at Timer.listOnTimeout (timers.js:92:15)
[Info] Sat, 13 Aug 2016 18:42:28 GMT wallaby:project Test run finished
[Info] Sat, 13 Aug 2016 18:42:28 GMT wallaby:project Test run data re-queued
```

```
module.exports = function (wallaby) {
  return {
    files: [
      'src/**/*.ts',
      '!src/**/*.unit.ts',
      '!src/**/*.integration.ts',
    ],

    tests: [
      'src/**/*.unit.ts',
    ],

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript({ module: 'commonjs' }),
    },

    env: {
      type: 'node'
    },

    testFramework: 'ava',

    debug: true,
  };
};
```

**Comment by ArtemGovorov** [comment]
Can't reproduce the issue, what is you wallaby.js core version (displayed first line in the debug output)? If it's not the latest (v1.0.278), try [forcing the update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update). If there's still an issue with the latest core, could you please share a sample github project where I could reproduce it?

**Comment by jperl** [comment]
Just forced an update but getting the same error. I will try to make a repro project.

```
[Info] Started Wallaby.js Core v1.0.168
[Info] Sun, 14 Aug 2016 02:13:57 GMT wallaby:fs File added: src/settings.ts
[Info] Sun, 14 Aug 2016 02:13:57 GMT wallaby:fs File added: src/entities/DbClient.ts
[Info] Sun, 14 Aug 2016 02:13:57 GMT wallaby:fs File added: src/entities/Entities.ts
[Info] Sun, 14 Aug 2016 02:13:57 GMT wallaby:fs File added: src/entities/Jobs.ts
[Info] Sun, 14 Aug 2016 02:13:57 GMT wallaby:fs File added: src/entities/Schema.ts
[Info] Sun, 14 Aug 2016 02:13:57 GMT wallaby:fs File added: src/entities/SyncPlans.ts
[Info] Sun, 14 Aug 2016 02:13:57 GMT wallaby:fs File added: src/entry/cli.ts
[Info] Sun, 14 Aug 2016 02:13:57 GMT wallaby:fs File added: src/entry/lambda.ts
[Info] Sun, 14 Aug 2016 02:13:57 GMT wallaby:fs File added: src/rets/Dmql.ts
[Info] Sun, 14 Aug 2016 02:13:57 GMT wallaby:fs File added: src/rets/Dmql.unit.ts
[Info] Sun, 14 Aug 2016 02:13:57 GMT wallaby:fs File added: src/rets/IListing.ts
[Info] Sun, 14 Aug 2016 02:13:57 GMT wallaby:fs File added: src/rets/IListingQuery.ts
[Info] Sun, 14 Aug 2016 02:13:57 GMT wallaby:fs File added: src/rets/IOperator.ts
[Info] Sun, 14 Aug 2016 02:13:57 GMT wallaby:fs File added: src/rets/IOperator.unit.ts
[Info] Sun, 14 Aug 2016 02:13:57 GMT wallaby:fs File added: src/rets/MrisClient.ts
[Info] Sun, 14 Aug 2016 02:13:57 GMT wallaby:fs File added: src/sync/Orchestrator.ts
[Info] Sun, 14 Aug 2016 02:13:57 GMT wallaby:fs File added: src/sync/Orchestrator.unit.ts
[Info] Sun, 14 Aug 2016 02:13:57 GMT wallaby:fs File added: src/sync/Worker.ts
[Info] Sun, 14 Aug 2016 02:13:58 GMT wallaby:project File cache: /Users/jperl/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.20/projects/870e85fe16117fea
[Info] Sun, 14 Aug 2016 02:13:58 GMT wallaby:workers Parallelism for initial run: 6, for regular run: 3
[Info] Sun, 14 Aug 2016 02:13:58 GMT wallaby:workers Starting run worker instance #0
[Info] Sun, 14 Aug 2016 02:13:58 GMT wallaby:workers Starting run worker instance #1
[Info] Sun, 14 Aug 2016 02:13:58 GMT wallaby:workers Starting run worker instance #2
[Info] Sun, 14 Aug 2016 02:13:58 GMT wallaby:workers Starting run worker instance #3
[Info] Sun, 14 Aug 2016 02:13:58 GMT wallaby:workers Starting run worker instance #4
[Info] Sun, 14 Aug 2016 02:13:58 GMT wallaby:workers Starting run worker instance #5
[Info] Sun, 14 Aug 2016 02:13:58 GMT wallaby:workers Web server is listening at 56032
[Info] Sun, 14 Aug 2016 02:13:58 GMT wallaby:project Stopping process pool
[Info] Sun, 14 Aug 2016 02:13:58 GMT wallaby:project File cache is up-to-date, starting full test run
[Info] Sun, 14 Aug 2016 02:13:58 GMT wallaby:project Running postprocessor
[Info] Sun, 14 Aug 2016 02:13:58 GMT wallaby:postprocessor New TypeScript language service is required
[Info] Sun, 14 Aug 2016 02:13:58 GMT wallaby:project TypeError: e._compiler.getSourceFile is not a function
[Info]   at /Users/jperl/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.20/wallaby/server.js:18:4486
[Info]   at baseFor (/Users/jperl/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.20/wallaby/node_modules/lodash/index.js:1971:13)
[Info]   at baseForOwn (/Users/jperl/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.20/wallaby/node_modules/lodash/index.js:2025:14)
[Info]   at baseEach (/Users/jperl/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.20/wallaby/node_modules/lodash/index.js:1814:16)
[Info]   at Function.forEach (/Users/jperl/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.20/wallaby/node_modules/lodash/index.js:5701:11)
[Info]   at Object.postprocessor (/Users/jperl/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.20/wallaby/server.js:18:3800)
[Info]   at /Users/jperl/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.20/wallaby/server.js:16:13886
[Info]   at [object Object]._onTimeout (/Users/jperl/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.20/wallaby/server.js:16:13488)
[Info]   at Timer.listOnTimeout (timers.js:92:15)
[Info] From previous event:
[Info]   at [object Object]._onTimeout (/Users/jperl/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.20/wallaby/server.js:16:13488)
[Info]   at Timer.listOnTimeout (timers.js:92:15)
[Info] Sun, 14 Aug 2016 02:13:58 GMT wallaby:project Test run finished
[Info] Sun, 14 Aug 2016 02:13:58 GMT wallaby:project Test run data re-queued
[Info] Sun, 14 Aug 2016 02:13:58 GMT wallaby:workers Started run worker instance (delayed) #3
[Info] Sun, 14 Aug 2016 02:13:58 GMT wallaby:workers Started run worker instance (delayed) #5
[Info] Sun, 14 Aug 2016 02:13:58 GMT wallaby:workers Started run worker instance (delayed) #0
[Info] Sun, 14 Aug 2016 02:13:58 GMT wallaby:workers Started run worker instance (delayed) #4
[Info] Sun, 14 Aug 2016 02:13:58 GMT wallaby:workers Started run worker instance (delayed) #2
[Info] Sun, 14 Aug 2016 02:13:58 GMT wallaby:workers Started run worker instance (delayed) #1
```

**Comment by jperl** [comment]
Here is a repro project https://github.com/jperl/wallaby-repro.git. I am using VSCode.

**Comment by ArtemGovorov** [comment]
> Started Wallaby.js Core v1.0.168

Your wallaby.js core version is not the latest (not the one where TypeScript 2.0 is supported). Is your wallaby license up-to-date, when did you purchase the license?

**Comment by jperl** [comment]
Updating my license fixed it. Thank you!
